name       : dar
version    : 2.5.11
release    : 5
source     :
    - https://netcologne.dl.sourceforge.net/project/dar/dar/2.5.11/dar-2.5.11.tar.gz : ad9d4b32b7a1240d9ae74155ff0aab3848065bee65ce01a022a234c02be73989
license    : GPL-2.0
component  : system.utils
summary    : A full featured command-line backup tool, short for Disk ARchive
description: |
    DAR is a command line tool to backup a directory tree and files. DAR is
    able to make differential backups, split them over a set of disks or files
    of a given size, use compression, filter files or subtrees to be saved or
    not saved, directly access and restore given files. DAR is also able
    to handle extented attributes, and can make remote backups through an
    ssh session for example. Finally, DAR handles save and restore of hard
    and symbolic links.
builddeps  :
    - pkgconfig(ext2fs)
    - attr-devel
    - gpgme-devel
    - libassuan-devel
    - lzo-devel
setup      : |
    %configure --disable-static \
               --disable-dar-static \
               --disable-build-html \
               --enable-mode=64
build      : |
    %make
install    : |
    %make_install
